const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const DEFAULT_ERROR = 500;
const CONFLICT_ERROR = 409;
const UNAUTHORIZED = 401;
const NO_PERMISSION = 403;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  DEFAULT_ERROR,
  CONFLICT_ERROR,
  UNAUTHORIZED,
  NO_PERMISSION,
};
